<?php

/**
 * Implementation Of hook_form_alter()
 */
function custom_html_mail_form_alter(&$form, &$form_state, $form_id) {

  switch ($form_id) {
    case 'views_form_email_users_page':
      //I3 Admin Email Users View
      if ( isset($form['recipient']) || (isset($form['to']) && $form['to']['#title'] == 'Recipient') ) {
        //dsm($form);

        //Mail Key
        $form['key'] = array(
          '#type' => 'select',
          '#title' => t('E-mail Template'),
          '#options' => array(
            'default' => t('Default One Column Template'),
          ),
          '#default_value' => 'default',
          '#description' => t('Use this dropdown to select what template you would like to use to send out this email.'),
          '#required' => TRUE,
        );

        //Mail To
        $form['to']['#default_value'] = '[user:mail]';
        $form['to']['#disabled'] = TRUE;

        //Mail Reply-to
        $form['reply-to']['#default_value'] = 'dev@informatics-studio.com';

        //Mail Body
        $form['body']['#format'] = 'full_html';

        //Mail Hide Fields
        $form['cc']['#attributes']['class'] = array('element-hidden');
        $form['bcc']['#attributes']['class'] = array('element-hidden');
        $form['attachments']['#attributes']['class'] = array('element-hidden');

        //Fields Access
        $form['cc']['#access'] = FALSE;
        $form['bcc']['#access'] = FALSE;
        $form['attachments']['#access'] = FALSE;

      }
      //dsm($form);
      break;
  }

}

/**
 * Implements hook_views_api().
 */
function custom_html_mail_views_api() {
  return array('api' => 3.0);
}

/**
 * Implements hook_views_default_views().
 */
function custom_html_mail_views_default_views() {
  $roles = array(
    3 => '3',
    4 => '4',
  );

  // exported view goes here
    $view = new view();
    $view->name = 'email_users';
    $view->description = '';
    $view->tag = 'default';
    $view->base_table = 'users';
    $view->human_name = 'Email Users';
    $view->core = 7;
    $view->api_version = '3.0';
    $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

    /* Display: Master */
    $handler = $view->new_display('default', 'Master', 'default');
    $handler->display->display_options['title'] = 'Email Users';
    $handler->display->display_options['use_more_always'] = FALSE;
    $handler->display->display_options['access']['type'] = 'role';
    $handler->display->display_options['access']['role'] = array(
      5 => '5',
      3 => '3',
      6 => '6',
      4 => '4',
    );
    $handler->display->display_options['cache']['type'] = 'none';
    $handler->display->display_options['query']['type'] = 'views_query';
    $handler->display->display_options['exposed_form']['type'] = 'basic';
    $handler->display->display_options['pager']['type'] = 'full';
    $handler->display->display_options['pager']['options']['items_per_page'] = '50';
    $handler->display->display_options['style_plugin'] = 'table';
    $handler->display->display_options['style_options']['columns'] = array(
      'uid' => 'uid',
      'views_bulk_operations' => 'views_bulk_operations',
      'name' => 'name',
      'realname' => 'realname',
      'mail' => 'mail',
      'created' => 'created',
      'access' => 'access',
      'login' => 'login',
      'rid' => 'rid',
      'edit_node' => 'edit_node',
    );
    $handler->display->display_options['style_options']['default'] = 'uid';
    $handler->display->display_options['style_options']['info'] = array(
      'uid' => array(
        'sortable' => 1,
        'default_sort_order' => 'asc',
        'align' => '',
        'separator' => '',
        'empty_column' => 0,
      ),
      'views_bulk_operations' => array(
        'align' => '',
        'separator' => '',
        'empty_column' => 0,
      ),
      'name' => array(
        'sortable' => 1,
        'default_sort_order' => 'asc',
        'align' => '',
        'separator' => '',
        'empty_column' => 0,
      ),
      'realname' => array(
        'sortable' => 1,
        'default_sort_order' => 'asc',
        'align' => '',
        'separator' => '',
        'empty_column' => 0,
      ),
      'mail' => array(
        'sortable' => 1,
        'default_sort_order' => 'asc',
        'align' => '',
        'separator' => '',
        'empty_column' => 0,
      ),
      'created' => array(
        'sortable' => 1,
        'default_sort_order' => 'asc',
        'align' => '',
        'separator' => '',
        'empty_column' => 0,
      ),
      'access' => array(
        'sortable' => 1,
        'default_sort_order' => 'asc',
        'align' => '',
        'separator' => '',
        'empty_column' => 0,
      ),
      'login' => array(
        'sortable' => 1,
        'default_sort_order' => 'asc',
        'align' => '',
        'separator' => '',
        'empty_column' => 0,
      ),
      'rid' => array(
        'align' => '',
        'separator' => '',
        'empty_column' => 0,
      ),
      'edit_node' => array(
        'align' => '',
        'separator' => '',
        'empty_column' => 0,
      ),
    );
    /* Field: User: Uid */
    $handler->display->display_options['fields']['uid']['id'] = 'uid';
    $handler->display->display_options['fields']['uid']['table'] = 'users';
    $handler->display->display_options['fields']['uid']['field'] = 'uid';
    $handler->display->display_options['fields']['uid']['label'] = 'Id';
    $handler->display->display_options['fields']['uid']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['uid']['link_to_user'] = FALSE;
    /* Field: Bulk operations: User */
    $handler->display->display_options['fields']['views_bulk_operations']['id'] = 'views_bulk_operations';
    $handler->display->display_options['fields']['views_bulk_operations']['table'] = 'users';
    $handler->display->display_options['fields']['views_bulk_operations']['field'] = 'views_bulk_operations';
    $handler->display->display_options['fields']['views_bulk_operations']['label'] = 'Select';
    $handler->display->display_options['fields']['views_bulk_operations']['vbo_settings']['display_type'] = '0';
    $handler->display->display_options['fields']['views_bulk_operations']['vbo_settings']['enable_select_all_pages'] = 1;
    $handler->display->display_options['fields']['views_bulk_operations']['vbo_settings']['force_single'] = 0;
    $handler->display->display_options['fields']['views_bulk_operations']['vbo_settings']['entity_load_capacity'] = '10';
    $handler->display->display_options['fields']['views_bulk_operations']['vbo_operations'] = array(
      'action::user_block_user_action' => array(
        'selected' => 0,
        'postpone_processing' => 0,
        'skip_confirmation' => 0,
        'override_label' => 0,
        'label' => '',
      ),
      'action::views_bulk_operations_user_cancel_action' => array(
        'selected' => 0,
        'postpone_processing' => 0,
        'skip_confirmation' => 0,
        'override_label' => 0,
        'label' => '',
      ),
      'action::role_delegation_delegate_roles_action' => array(
        'selected' => 0,
        'postpone_processing' => 0,
        'skip_confirmation' => 0,
        'override_label' => 0,
        'label' => '',
      ),
      'action::views_bulk_operations_delete_item' => array(
        'selected' => 0,
        'postpone_processing' => 0,
        'skip_confirmation' => 0,
        'override_label' => 0,
        'label' => '',
      ),
      'action::views_bulk_operations_delete_revision' => array(
        'selected' => 0,
        'postpone_processing' => 0,
        'skip_confirmation' => 0,
        'override_label' => 0,
        'label' => '',
      ),
      'action::views_bulk_operations_script_action' => array(
        'selected' => 0,
        'postpone_processing' => 0,
        'skip_confirmation' => 0,
        'override_label' => 0,
        'label' => '',
      ),
      'action::flag_user_action' => array(
        'selected' => 0,
        'postpone_processing' => 0,
        'skip_confirmation' => 0,
        'override_label' => 0,
        'label' => '',
      ),
      'action::views_bulk_operations_modify_action' => array(
        'selected' => 0,
        'postpone_processing' => 0,
        'skip_confirmation' => 0,
        'override_label' => 0,
        'label' => '',
        'settings' => array(
          'show_all_tokens' => 1,
          'display_values' => array(
            '_all_' => '_all_',
          ),
        ),
      ),
      'action::views_bulk_operations_user_roles_action' => array(
        'selected' => 0,
        'postpone_processing' => 0,
        'skip_confirmation' => 0,
        'override_label' => 0,
        'label' => '',
      ),
      'action::views_bulk_operations_argument_selector_action' => array(
        'selected' => 0,
        'skip_confirmation' => 0,
        'override_label' => 0,
        'label' => '',
        'settings' => array(
          'url' => '',
        ),
      ),
      'action::system_send_email_action' => array(
        'selected' => 0,
        'postpone_processing' => 0,
        'skip_confirmation' => 0,
        'override_label' => 0,
        'label' => '',
      ),
      'action::mimemail_send_email_action' => array(
        'selected' => 1,
        'postpone_processing' => 0,
        'skip_confirmation' => 0,
        'override_label' => 0,
        'label' => '',
      ),
      'action::realname_action_realname_update' => array(
        'selected' => 0,
        'postpone_processing' => 0,
        'skip_confirmation' => 0,
        'override_label' => 0,
        'label' => '',
      ),
      'action::pathauto_user_update_action' => array(
        'selected' => 0,
        'postpone_processing' => 0,
        'skip_confirmation' => 0,
        'override_label' => 0,
        'label' => '',
      ),
    );
    /* Field: User: Name */
    $handler->display->display_options['fields']['name']['id'] = 'name';
    $handler->display->display_options['fields']['name']['table'] = 'users';
    $handler->display->display_options['fields']['name']['field'] = 'name';
    $handler->display->display_options['fields']['name']['label'] = 'User Name';
    /* Field: Realname: Real name */
    $handler->display->display_options['fields']['realname']['id'] = 'realname';
    $handler->display->display_options['fields']['realname']['table'] = 'realname';
    $handler->display->display_options['fields']['realname']['field'] = 'realname';
    $handler->display->display_options['fields']['realname']['label'] = 'Full Name';
    /* Field: User: E-mail */
    $handler->display->display_options['fields']['mail']['id'] = 'mail';
    $handler->display->display_options['fields']['mail']['table'] = 'users';
    $handler->display->display_options['fields']['mail']['field'] = 'mail';
    /* Field: User: Created date */
    $handler->display->display_options['fields']['created']['id'] = 'created';
    $handler->display->display_options['fields']['created']['table'] = 'users';
    $handler->display->display_options['fields']['created']['field'] = 'created';
    $handler->display->display_options['fields']['created']['date_format'] = 'month_d_year_time_m';
    /* Field: User: Last access */
    $handler->display->display_options['fields']['access']['id'] = 'access';
    $handler->display->display_options['fields']['access']['table'] = 'users';
    $handler->display->display_options['fields']['access']['field'] = 'access';
    $handler->display->display_options['fields']['access']['date_format'] = 'month_d_year_time_m';
    /* Field: User: Last login */
    $handler->display->display_options['fields']['login']['id'] = 'login';
    $handler->display->display_options['fields']['login']['table'] = 'users';
    $handler->display->display_options['fields']['login']['field'] = 'login';
    $handler->display->display_options['fields']['login']['date_format'] = 'month_d_year_time_m';
    /* Field: User: Roles */
    $handler->display->display_options['fields']['rid']['id'] = 'rid';
    $handler->display->display_options['fields']['rid']['table'] = 'users_roles';
    $handler->display->display_options['fields']['rid']['field'] = 'rid';
    $handler->display->display_options['fields']['rid']['label'] = 'Users Roles';
    /* Field: User: Edit link */
    $handler->display->display_options['fields']['edit_node']['id'] = 'edit_node';
    $handler->display->display_options['fields']['edit_node']['table'] = 'users';
    $handler->display->display_options['fields']['edit_node']['field'] = 'edit_node';
    $handler->display->display_options['fields']['edit_node']['label'] = 'Edit';
    /* Sort criterion: User: Created date */
    $handler->display->display_options['sorts']['created']['id'] = 'created';
    $handler->display->display_options['sorts']['created']['table'] = 'users';
    $handler->display->display_options['sorts']['created']['field'] = 'created';
    $handler->display->display_options['sorts']['created']['order'] = 'DESC';
    /* Filter criterion: User: Active */
    $handler->display->display_options['filters']['status']['id'] = 'status';
    $handler->display->display_options['filters']['status']['table'] = 'users';
    $handler->display->display_options['filters']['status']['field'] = 'status';
    $handler->display->display_options['filters']['status']['value'] = '1';
    $handler->display->display_options['filters']['status']['group'] = 1;
    $handler->display->display_options['filters']['status']['exposed'] = TRUE;
    $handler->display->display_options['filters']['status']['expose']['operator_id'] = '';
    $handler->display->display_options['filters']['status']['expose']['label'] = 'Active User';
    $handler->display->display_options['filters']['status']['expose']['operator'] = 'status_op';
    $handler->display->display_options['filters']['status']['expose']['identifier'] = 'status';
    $handler->display->display_options['filters']['status']['expose']['required'] = TRUE;
    $handler->display->display_options['filters']['status']['expose']['remember_roles'] = array(
      2 => '2',
      1 => 0,
      5 => 0,
      7 => 0,
      3 => 0,
      4 => 0,
    );
    /* Filter criterion: Realname: Name */
    $handler->display->display_options['filters']['realname']['id'] = 'realname';
    $handler->display->display_options['filters']['realname']['table'] = 'realname';
    $handler->display->display_options['filters']['realname']['field'] = 'realname';
    $handler->display->display_options['filters']['realname']['operator'] = 'contains';
    $handler->display->display_options['filters']['realname']['group'] = 1;
    $handler->display->display_options['filters']['realname']['exposed'] = TRUE;
    $handler->display->display_options['filters']['realname']['expose']['operator_id'] = 'realname_op';
    $handler->display->display_options['filters']['realname']['expose']['label'] = 'Name Search';
    $handler->display->display_options['filters']['realname']['expose']['operator'] = 'realname_op';
    $handler->display->display_options['filters']['realname']['expose']['identifier'] = 'realname';
    $handler->display->display_options['filters']['realname']['expose']['remember_roles'] = array(
      2 => '2',
      1 => 0,
      5 => 0,
      7 => 0,
      3 => 0,
      4 => 0,
    );
    /* Filter criterion: User: E-mail */
    $handler->display->display_options['filters']['mail']['id'] = 'mail';
    $handler->display->display_options['filters']['mail']['table'] = 'users';
    $handler->display->display_options['filters']['mail']['field'] = 'mail';
    $handler->display->display_options['filters']['mail']['operator'] = 'contains';
    $handler->display->display_options['filters']['mail']['group'] = 1;
    $handler->display->display_options['filters']['mail']['exposed'] = TRUE;
    $handler->display->display_options['filters']['mail']['expose']['operator_id'] = 'mail_op';
    $handler->display->display_options['filters']['mail']['expose']['label'] = 'E-mail';
    $handler->display->display_options['filters']['mail']['expose']['operator'] = 'mail_op';
    $handler->display->display_options['filters']['mail']['expose']['identifier'] = 'mail';
    $handler->display->display_options['filters']['mail']['expose']['remember_roles'] = array(
      2 => '2',
      1 => 0,
      5 => 0,
      7 => 0,
      3 => 0,
      4 => 0,
    );
    /* Filter criterion: User: Roles */
    $handler->display->display_options['filters']['rid']['id'] = 'rid';
    $handler->display->display_options['filters']['rid']['table'] = 'users_roles';
    $handler->display->display_options['filters']['rid']['field'] = 'rid';
    $handler->display->display_options['filters']['rid']['group'] = 1;
    $handler->display->display_options['filters']['rid']['exposed'] = TRUE;
    $handler->display->display_options['filters']['rid']['expose']['operator_id'] = 'rid_op';
    $handler->display->display_options['filters']['rid']['expose']['label'] = 'Site Roles';
    $handler->display->display_options['filters']['rid']['expose']['use_operator'] = TRUE;
    $handler->display->display_options['filters']['rid']['expose']['operator'] = 'rid_op';
    $handler->display->display_options['filters']['rid']['expose']['identifier'] = 'rid';
    $handler->display->display_options['filters']['rid']['expose']['multiple'] = TRUE;
    $handler->display->display_options['filters']['rid']['expose']['remember_roles'] = array(
      2 => '2',
      1 => 0,
      5 => 0,
      3 => 0,
    );
    $handler->display->display_options['filters']['rid']['reduce_duplicates'] = TRUE;

    /* Display: Page */
    $handler = $view->new_display('page', 'Page', 'page');
    $handler->display->display_options['path'] = 'admin/site-admin/users/email-users';

  // end exported view code

  $views[$view->name] = $view;
  // return views
  return $views;
}

/**
 * Implements hook_cron().
 */
function custom_html_mail_cron() {
  if (module_exists('less')) {
    //Include Less Library
    _less_inc();
    //Directory where file will be placed create it if needed
    $wysiwyg_render_path = 'public://mail_css_render';
    $is_dir = is_dir($wysiwyg_render_path);
    if (!$is_dir) {
      $is_dir = file_prepare_directory($wysiwyg_render_path, FILE_CREATE_DIRECTORY);
    }
    //Location of the wysiwyg-render.less
    $input_file = drupal_get_path('theme', variable_get('theme_default', NULL)).'/less/mail-render.less';

    //Ensure file exists
    if (is_file($input_file) && $is_dir) {
      $output_file = $wysiwyg_render_path . '/' . basename($input_file, '.less').'.css';

      $less = new lessc();

      $less->registerFunction('token', ' _less_token_replace');
      $output_data = $less->compileFile($input_file);
      // Fix paths for images as .css is in different location.
      $output_data = _less_rewrite_paths($input_file, $output_data);
      // Output the file
      file_unmanaged_save_data($output_data, $output_file, FILE_EXISTS_REPLACE);

      $message = 'Custom MAIL Less File Generated: %input_file';
      $message_vars = array('%input_file' => $input_file);
      watchdog('custom_css_ckeditor', $message, $message_vars, WATCHDOG_INFO);
    }
  }
}
