<?php
/**
 * Implements hook_environment_switch().
 * In DRUSH Use:
 * drush env-switch development 
 * drush env-switch production
 */
function custom_env_environment_switch($target_env, $current_env) {
  // Declare each optional development-related module
  $devel_modules = array(
    'context_ui',
    'devel',
    'devel_generate',
    'devel_node_access',
    'imagecache_ui',
    'update',
    'hacked',
    'views_ui',
  );
  
  $production_modules = array(
  );

  switch ($target_env) {
    case 'production':
      module_disable($devel_modules);
      drupal_set_message('Disabled development modules');
      module_enable($production_modules);
      drupal_set_message('Enabled production modules');
      return;
    case 'development':
      module_enable($devel_modules);
      drupal_set_message('Enabled development modules');
      module_disable($production_modules);
      drupal_set_message('Disabled production modules');
      return;
  }
}
?>